# Base configs
baseurl: "https://goonerboy49.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Goonerboy49"
subtitle: "Private photography site"
author: "Goonerboy49"
header:
 title: "Photography"
 subtitle: "by Goonerboy49"
footer:
 name: "Hey there"
 bio: "Biking, photography, coding, eating, husband, dad in no particular order."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
theme: jekyll-theme-cayman
